### ISSUE TITLE
BUG: Non recursive schema resolves as "any" and fails the build 

### ISSUE THREAD

**Issue by mrded** [ThomasAribart/json-schema-to-ts#146] opened 2023-05-25 18:12 UTC
- json-schema-to-ts: 2.9.0
- node: 18.13.0
- typescript: 4.2.3

I'm trying to turn into types a very basic schema:
```typescript
const responseSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    success: { type: 'boolean' },
    statusCode: { type: 'number' },
    message: { type: 'string' }
  },
  required: ['success', 'statusCode', 'message']
} as const;

type Response = FromSchema<typeof responseSchema>;
```

Which resolves as `any`.

When I try to build it, it fails with `TS2589: Type instantiation is excessively deep and possibly infinite.` error.

![image](https://github.com/ThomasAribart/json-schema-to-ts/assets/347098/bfdf7d7d-f9eb-4fdc-9ac8-792ea4e084ce)

**Comment by ThomasAribart** [comment] 2023-05-25 22:11
@mrded Yes it's a known issue, will be working on this tomorrow. Closing this as it's a duplicate of https://github.com/ThomasAribart/json-schema-to-ts/issues/144

**Closed by ThomasAribart** 2023-05-25 22:11 UTC
