### ISSUE TITLE
Regression in 2.8.0

### ISSUE THREAD

**Issue by daffl** [ThomasAribart/json-schema-to-ts#133] opened 2023-04-20 17:40 UTC
Initially reported in https://github.com/feathersjs/feathers/issues/3168, the 2.8.0 release produces the following error in all Feathers apps that are using `json-schema-to-ts`:

```
node_modules/json-schema-to-ts/lib/types/index.d.ts:16:314 - error TS2590: Expression produces a union type that is too complex to represent.
```

I didn't have much of a chance to look into it and since there isn't a Changelog I can't really tell what changed but wanted to flag the problem it since it comes up a lot now.

**Comment by daffl** [comment] 2023-04-20 20:46
I just noticed that this is probably the same as https://github.com/ThomasAribart/json-schema-to-ts/issues/132

**Comment by ThomasAribart** [comment] 2023-05-09 09:57
Hey ! Sorry I was on holiday but will put this in high prio !

Will try to fix this this week-end. Do you have an example of failing schema ? Or does the error just suddenly happens ?

**Comment by ThomasAribart** [comment] 2023-05-09 09:58
Actually, closing this as it is a duplicate of https://github.com/ThomasAribart/json-schema-to-ts/issues/132

**Closed as completed by ThomasAribart** 2023-05-09 09:58 UTC

**Comment by ThomasAribart** [comment] 2023-05-10 23:36
Should be fixed in 2.8.2
